name: Feature Request
description: File a bug report
labels: [Feature, triage-required]
body:
  - type: markdown
    id: intro-md
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! dbatools is testing out a beta of the [new Issues Forms](https://github.blog/changelog/2021-06-23-whats-new-with-github-issues/).

        Please ensure you provide as much information as asked to better assist in confirming and identifying a fix for the bug report.
  - type: textarea
    attributes:
      label: "Summary of new feature"
      description: "Please provide a clear/concise description of what problem this feature can solve."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Technical Details"
      description: "Provide links to concepts, example code or write-ups of the desired functionality."
    validations:
      required: false
